name: latexmk
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.1.20
        with:
          packages: xkeyval libertine framed tcolorbox environ tcolorbox listingsutf8 ffcode minted fvextra catchfile xstring
