---
name: markdown-lint
'on':
  push:
jobs:
  markdown-lint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: articulate/actions-markdownlint@v1
